version: '2'
services:
    dbclient:
        image: postgres:9.5
        depends_on:
            - db
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
        volumes:
            - "./backups:/backups"